export const SEARCH_MUSIC_LOADING = 'SEARCH_MUSIC_LOADING';
export const SEARCH_MUSIC_SUCCESS = 'SEARCG_MUSIC_SUCCESS';
export const SEARCH_MUSIC_ERROR = 'SEARCH_MUSIC_ERROR';
export const SEARCH_MUSIC_SORT_LIST = 'SEARCH_MUSIC_SORT_LIST';
export const SEARCH_MUSIC_OPEN_DETAIL = 'SEARCH_MUSIC_OPEN_DETAIL';
export const SEARCH_MUSIC_CLOSE_DETAIL = 'SEARCH_MUSIC_CLOSE_DETAIL';
